### ISSUE TITLE
Course news are truncated

### ISSUE THREAD

**Issue by Taikelenn** [Aalto-LeTech/aplus-courses#811]
If the news entry is long and doesn't fit inside one line, then it becomes truncated in the course news tool window. Preferably, if expanded by the user, the entry should span several lines if it's too long.

**Comment by jaakkonarhi** [comment]
it spans several lines for me

**Comment by jaakkonarhi** [comment]
![image](https://user-images.githubusercontent.com/34682147/145403207-5dbf43d7-ea31-44e5-a51a-3b0965256928.png)

**Comment by jsorva** [comment]
Looks like this for me (Win, IJ 2021.3, plugin v3.4). 
![image](https://user-images.githubusercontent.com/8523129/145403591-3e36c919-be20-46b9-9b12-c8d7bba04c44.png)

**Comment by Taikelenn** [comment]
Seems to be a problem on Windows, I checked on an Ubuntu VM and it looks good there.

**Comment by Taikelenn** [comment]
![obraz](https://user-images.githubusercontent.com/73069541/145425303-b53efa16-6930-4313-9019-e2f4b9752f7b.png)
Although if I first open the news, and then shrink the A+ Courses tool window, then it doesn't auto-adjust.

**Comment by OlliKiljunen** [comment]
This seems to be a problem of IntelliJ's [MultilineTreeCellRenderer](https://github.com/JetBrains/intellij-community/blob/213.6461/platform/platform-impl/src/com/intellij/ui/MultilineTreeCellRenderer.java).

On my Windows 10, it calculates the wrapped lines and their dimensions correctly but when the row is painted, it's given a `Graphics` object whose area is restricted to a size of single line row. [Here](https://github.com/JetBrains/intellij-community/blob/213.6461/platform/platform-impl/src/com/intellij/ui/MultilineTreeCellRenderer.java#L166), `Graphics.drawString()` is called for each of a row's wrapped lines but all except the first one of the calls are ineffective because the `SunGraphics2D` object that does the painting only paints to rectangle covering the first line.

Why does the `Graphics` object get a wrong painting area? One should probably take a look at [here](https://github.com/JetBrains/intellij-community/blob/213.6461/platform/platform-impl/src/com/intellij/ui/tree/ui/DefaultTreeUI.java#L254). The bounds for the row are read from a layout cache, `treeState`, but it apparently holds incorrect heights. Where are those heights updated, I don't know.
