### ISSUE TITLE
BannerView modifying final field

### ISSUE THREAD

**Issue by jaakkonarhi** [Aalto-LeTech/aplus-courses#841]

**Comment by Taikelenn** [comment]
Clearly, what Jaakko means by this issue, is that IntelliJ IDEA 2022 made the EditorNotificationPanel::myBackgroundColor field final. Since we're modifying that field inside a class MyEditorNotificationPanel, our plugin is incompatible with IntelliJ 2022 unless this is fixed.

**Comment by jaakkonarhi** [comment]
yes that's what the title says

**Comment by OlliKiljunen** [comment]
Storing the `backgroundColor` in a non-final field of `MyEditorNotificationPanel` and then overriding `getOverriddenBackgroundColor()` could _possibly_ work but the said method is annotated with `@ApiStatus.Internal`. 🤔 We could consider it as a hack...

**Comment by Taikelenn** [comment]
This is where I complain about all the bindables and observable properties that I ~~don't understand~~ dislike :pp

Could we just make the banner color a part of BannerView constructor? Or if we want to keep it bindable, maybe we need to change the `colorBindable` so that when the color is changed, a new banner is constructed with the new color (and the old one removed)

**Comment by Taikelenn** [comment]
I'll try to implement the second method

**Comment by OlliKiljunen** [comment]
> This is where I complain about all the bindables and observable properties that I ~~don't understand~~ dislike :pp
> Could we just make the banner color a part of BannerView constructor? Or if we want to keep it bindable, maybe we need to change the `colorBindable` so that when the color is changed, a new banner is constructed with the new color (and the old one removed)

The question whether it is bindable or not is secondary; first we should know/decide whether it can be changed during a lifetime of a `BannerView`. (It's becoming apparent that `MyEditorNotificationPanel` only serves this one class and should be a nested class of it.)

But even before that, there's an even more important question: **Why do we use `EditorNotificationPanel` instead of a plain `JPanel`?** (We don't even use it for _editor_ notifications!)
