### ISSUE TITLE
Scala 3 REPL blank lines

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#848]
In the Scala 3 REPL, paste code with blank lines and ending with `end Foo` clause. REPL gets confused, Juha reports.

Try on different platforms, report if necessary.

**Comment by OlliKiljunen** [comment]
Juha advised us to wait for extra refinement from him before tackling this.

**Comment by jsorva** [comment]
Right, so I’ve discovered some more details about this than I initially verbally reported. It seems that the behavior appears only in some circumstances and is related to indentation levels rather than pasting. (But due to the nature of the problem, it occurs in practice when pasting code, not when typing it in the REPL.)

Based on what I’ve tried so far on my machine, the error seems to appear under these specific (but common) conditions: 

1. Using IJ’s REPL. (The standard command-line REPL works fine, even when pasting.); and 

2. Using Scala 3’s new significant-indentation syntax with end markers. (Code with old-style curly braces, which is still valid in Scala 3, seems to work fine.); and 

3. There’s something other than whitespace within the construct—let’s say a class—that the end marker ends. (An empty class definition with blank lines works fine.); and

5. There’s a blank line somewhere within the class, except that the very top of the class body doesn’t count. (If all the blanks are at the top, things seem to work fine(?).); and 

6. The blank lines do not contain space characters to match the block’s indentation level. (If they do contain the spaces, things work fine.)

I.e., these fail when pasted into IJ’s REPL on my machine:

```
// blank line at the bottom, none at the top
class Foo:
  def foo = ???
  def bar = ??? 

end Foo
```

```
// blank somewhere in the middle
class Foo:
  def foo = ???

  def bar = ??? 
end Foo
```

But these work:

```
// no blanks
class Foo:
  def foo = ???
  def bar = ??? 
end Foo
```

```
// blanks, old-style curlies
class Foo {

 def foo = ???

 def bar = ???

}
```

``` 
// nothing but blank(s) in class
class Foo:


end Foo
```

```
// blank line(s) at the top but no blank elsewhere
class Foo:

  def foo = ???
  def bar = ??? 
end Foo
```

```
// blank somewhere in the middle BUT with two space characters on the blank line
class Foo:
  def foo = ???
  
  def bar = ??? 
end Foo
```

As a special case, this fails differently (producing a class with `foo` plus a separate `bar` that’s not a member of the class):

```
// blank line in the middle, NO END MARKER
class Foo:
  def foo = ???

  def bar = ???
```

**Comment by jsorva** [comment]
So if others can replicate this, I suppose the verdict is that IJ’s REPL fails to deal with indentation on blank lines appropriately and should be fixed.

**Comment by Taikelenn** [comment]
I am observing the same behaviour on Windows and Ubuntu. My personal gut feeling is that it's somehow related to https://youtrack.jetbrains.com/issue/SCL-19700

**Comment by jsorva** [comment]
> I am observing the same behaviour on Windows and Ubuntu. My personal gut feeling is that it's somehow related to https://youtrack.jetbrains.com/issue/SCL-19700

Could be, but possibly not: that issue is labelled "debugger", and it mentions "synthetic classes", which I suppose refers to implicitly created classes that are not explicitly defined as classes in Scala code.

**Comment by jsorva** [comment]
Hmm, I realize now that when I tried this in the command-line REPL, I was doing it in WSL2, so basically in Linux. There, things work fine, but in cmd.exe, they indeed don’t. 

It still feels like a bug to me. Or a very undesirable feature, at the very least. 

The Scala REPL used to have a special `:paste` command that one needed to use in some scenarios, but that’s obsolete now. 

Hmm, I found [this thread](https://users.scala-lang.org/t/solved-cannot-use-paste-in-scala3-repl/7587).

**Comment by Taikelenn** [comment]
I made a "proof of concept" draft PR #859 which modifies the console so that it does not split multiline statements, but rather sends it all at once to the REPL process. I even used a lower level Windows API inspector to verify that it works correctly (and it does).

Unfortunately, it didn't seem to have fixed anything. The example class definitions still fail in the same way. At this point I'm not sure if it's something that can even be fixed on the IntelliJ side. For what it's worth, the problem might be related to reading lines by the Scala 3 compiler. I'll try to investigate this further with a debugger under Linux

**Comment by Taikelenn** [comment]
https://youtrack.jetbrains.com/issue/SCL-20209/Proper-multiline-paste-support-for-Scala-REPL

**Comment by stellatsv** [comment]
Waiting for a response from JetBrains.

**Comment by stellatsv** [comment]
Check the situation at the end of June, and make the decision what to do (can the O1 course live with this?)
