### ISSUE TITLE
Two enters needed to end multiline REPL input (Scala 3)

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#887]
need to hit Ctrl+Enter (or just Enter, depending on settings?) twice to end multiline input

One should be enough

**Comment by Taikelenn** [comment]
Cannot reproduce - multiline input works fine for me (shift+enter goes to the next line, enter sends the whole text to REPL process)

**Comment by jsorva** [comment]
> Cannot reproduce - multiline input works fine for me (shift+enter goes to the next line, enter sends the whole text to REPL process). Perhaps has been already fixed?

Does this work for you?

1. Open the REPL
2. Type `def foo =` and end the line (Enter for me, Shift+Enter by default I guess)
3. Enter `  1+1` on the next line and try to send to REPL (Ctrl+Enter for me, Enter by default I guess)

If I do that, I get this:

![image](https://user-images.githubusercontent.com/8523129/166664283-5d476b8d-592a-438e-990c-bfe66e8f0d73.png)

That is, the function doesn’t get sent yet (or at least there’s no indication of it being sent). Only if I hit Ctrl+Enter again or enter some other code below does the REPL acknowledge that `foo` got defined.

**Comment by Taikelenn** [comment]
https://user-images.githubusercontent.com/73069541/166690961-01231835-9dd0-4f97-953a-8cc3bc21382f.mp4

I still cannot reproduce that (with or without A+ Courses installed). Using Enter and Ctrl+Enter doesn't make any difference. Using Shift+Enter correctly moves the cursor to the next line (without sending anything), since it's the multiline hotkey.

**Comment by jsorva** [comment]
In that example, the `1+1` isn’t indented. What if you indent it? For me, that seems to make a difference: it works if the code is (inappropriately) unindented but fails if it is indented.

**Comment by Taikelenn** [comment]
Okay, I see - when the `1+1` is indented, it waits for the next line. This also happens in the command-line REPL, so it's unrelated to IntelliJ here.

But shouldn't this be the expected behaviour for indentation-based languages? I mean, after writing an indented `1+1`, the REPL doesn't know if you're done. You could write this to get foo = 6:
```
def foo =
  1 + 1
  + 1 +
  1 +
  2
```
or, a less contrived example, using some kind of builder pattern
```
def battle =
  new BattleBuilder()
  .AddUnit(abc)
  .SetDifficulty(5)
  .Create()
```

Alternatively, the developers of Scala REPL could've gone the Python way and just decide that in REPL, `def foo = ` is an invalid syntax.

**Comment by jsorva** [comment]
> But shouldn't this be the expected behaviour for indentation-based languages?

If we’re talking about syntax and newlines only, sure. But here we have an environment with a command that is explicitly supposed to send the code for evaluation. The IJ command that runs when I—or O1 students—press Ctrl+Enter (and you press Enter) is _Execute Scala REPL Statement_; it’s not an editing command for adding something to the code.

**Comment by Taikelenn** [comment]
> But here we have an environment with a command that is explicitly supposed to send the code for evaluation.

Which is what is happening - IntelliJ sends each line for evaluation right after pressing Ctrl+Enter/Enter. It's not a "multiline mode", for example you aren't able to edit previous lines after submitting them (multiline statements are entered using Shift+Enter, at least for me). Try typing
```
def foo =
  =
```
and you'll be able to see that the REPL immediately complains; no need to enter a blank line. When you press Ctrl+Enter (or I press Enter), IntelliJ obediently sends every line to the REPL in real time.

It's the Scala 3 compiler itself (the underlying REPL process) that is refusing to execute the statement because it might expect more indented lines, so it waits until an unindented line appears. IntelliJ has no say here - REPL process is waiting, so IntelliJ must wait as well.

Theoretically, this behaviour could be changed by forcing an empty line to be sent when the user presses Ctrl+Enter. But even this won't solve all problems: for example, typing `class` (and a newline) in the REPL will "lock it up" - no amount of newlines will end the statement because the REPL expects a class name. Only after the user provides some class name, the statement can end.

**Comment by jsorva** [comment]
I believe you’re right if this is viewed from the technical perspective. It’s unfortunate.

From a usability perspective (IMO, anyway), "Sending to the REPL" should mean "I edited some multiline stuff here and now I’m going to send it to be evaluated. Really, this was everything that I’m going to type now, so stop asking for more input." For example, if I type just `class` and hit Ctrl+Enter, I should get a compilation error. You’re right that this is not how the REPL (in IJ or elsewhere) is set up to work, though. :-(

**Comment by stellatsv** [comment]
There are currently no actions to be done for this issue.
