### ISSUE TITLE
REPL warnings missing (Scala 3)

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/aplus-courses#888]
not all warnings shown — the REPL doesn’t respect Scala compiler flags?
(Ask Juha for examples, if needed)

**Comment by jsorva** [comment]
Here’s one example (which happens to not actually be warning but an error, but the concern is similar):

Say I write this in a file:

`def foo = if (true) 1 else 2`

That’s an example of old Scala 2 syntax, which is still accepted but discouraged in Scala 3 (and may eventually be completely invalid).  In Scala 3, I should write `if true then 1 else 2`.

In O1, I’d like to disable the old syntax altogether, which can be enforced with the compiler switch `-new-syntax`. If I switch that on in IJ _(Settings → Scala Compiler → Additional compiler options)_, the code fails to compile in Scala 3, which is good.

However, in the REPL, I can still write `if (true) 1 else 2`  and it works, which is bad. So the REPL obviously doesn’t obey the Scala compiler setting. Maybe that’s intentional, maybe not — I don’t know. If it is unintentional, I suppose it should be fixed in the Scala plugin. 

Anyway, we can work around this limitation. If I manually adjust the REPL run config for the module I’m working with and add a command-line option, the REPL does enforce the new syntax. Irrespective of whether the Scala plugin is modified, we could, in our plugin, allow teachers to set course-specific command-line options for the REPL.

(P.S. `-new-syntax` is not the only Scala 3 compiler option that I’d like to have on in the REPL.)

**Comment by Taikelenn** [comment]
@jsorva We'll try to make it so that REPL arguments can be configured by the teacher in the course configuration file. Before that, one question: is there any value in having specific REPL arguments for separate modules, or is one set of arguments applicable to all modules fine? (I guess the latter, but just wanted to make sure)

**Comment by jsorva** [comment]
> @jsorva We'll try to make it so that REPL arguments can be configured by the teacher in the course configuration file. Before that, one question: is there any value in having specific REPL arguments for separate modules, or is one set of arguments applicable to all modules fine? (I guess the latter, but just wanted to make sure)

I have no use cases in mind where it would make sense to have specific arguments for different modules within a single course.

**Comment by Taikelenn** [comment]
Good
